//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerDormitorySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASS_TB()
        {
            this.STUDENT_TB = new HashSet<STUDENT_TB>();
        }
    
        public decimal CLASS_ID { get; set; }
        public string CLASSNAME { get; set; }
        public decimal DEPARTMENT { get; set; }
    
        public virtual DEPARTMENT_TB DEPARTMENT_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_TB> STUDENT_TB { get; set; }
    }
}
