//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerDormitorySchool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerEntities : DbContext
    {
        public ManagerEntities()
            : base("name=ManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASS_TB> CLASS_TB { get; set; }
        public virtual DbSet<DEPARTMENT_TB> DEPARTMENT_TB { get; set; }
        public virtual DbSet<DEVVN_QUANHUYEN> DEVVN_QUANHUYEN { get; set; }
        public virtual DbSet<DEVVN_TINHTHANHPHO> DEVVN_TINHTHANHPHO { get; set; }
        public virtual DbSet<DEVVN_XAPHUONGTHITRAN> DEVVN_XAPHUONGTHITRAN { get; set; }
        public virtual DbSet<ROOM_TB> ROOM_TB { get; set; }
        public virtual DbSet<STATISTIC_TB> STATISTIC_TB { get; set; }
        public virtual DbSet<STUDENT_TB> STUDENT_TB { get; set; }
    }
}
