//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerDormitorySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_TB()
        {
            this.STATISTIC_TB = new HashSet<STATISTIC_TB>();
        }
    
        public string STUDENT_ID { get; set; }
        public string STUDENTNAME { get; set; }
        public decimal CLASS { get; set; }
        public decimal ROOM { get; set; }
        public decimal STATUS { get; set; }
        public Nullable<System.DateTime> DATEIN { get; set; }
        public Nullable<System.DateTime> DATEOUT { get; set; }
        public string PLACE { get; set; }
        public decimal PRIORITY { get; set; }
    
        public virtual CLASS_TB CLASS_TB { get; set; }
        public virtual ROOM_TB ROOM_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATISTIC_TB> STATISTIC_TB { get; set; }
    }
}
